# Generated by Django 2.1.1 on 2019-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, help_text='有值代表专项优惠券，没有值代表通用券', null=True, verbose_name='绑定的课程对象'),
        ),
    ]
