# Generated by Django 2.1.1 on 2019-05-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='account',
            field=models.OneToOneField(limit_choices_to={'level': 1}, on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='导师信息'),
        ),
    ]
