# Generated by Django 2.1.1 on 2019-05-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0002_auto_20190508_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='导师信息'),
        ),
    ]
