# Generated by Django 2.1.1 on 2019-04-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0003_auto_20190401_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete='cascade', related_name='course_detail', to='generic.Course'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='teacher',
            field=models.ManyToManyField(to='generic.Teacher', verbose_name='授课讲师'),
        ),
    ]
