# Generated by Django 2.1.1 on 2019-04-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0004_auto_20190402_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete='cascade', to='generic.Course'),
        ),
    ]
