# Generated by Django 2.1.1 on 2019-04-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0005_auto_20190402_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupondetail',
            options={'verbose_name': '用户优惠券领取使用记录表', 'verbose_name_plural': 'DB_CouponDetail'},
        ),
        migrations.AlterModelOptions(
            name='coursedetail',
            options={'verbose_name': '课程详情', 'verbose_name_plural': 'DB_CourseDetail'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.SmallIntegerField(choices=[(0, '通用券'), (1, '抵扣券'), (2, '满减券')], default=0, help_text='通用券为全局优惠券，其他则为专项券'),
        ),
        migrations.AlterModelTable(
            name='coupondetail',
            table='DB_CouponDetail',
        ),
    ]
