# Generated by Django 2.1.1 on 2019-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0006_auto_20190405_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='product',
            field=models.CharField(blank=True, help_text='如果是支出和退款一定写入购买的商品', max_length=64, null=True, verbose_name='商品名'),
        ),
    ]
