# Generated by Django 2.1.1 on 2019-04-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0007_traderecord_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderecord',
            name='product',
            field=models.CharField(blank=True, help_text='如果是支出和退款一定写入购买的商品', max_length=2048, null=True, verbose_name='商品名'),
        ),
    ]
