# Generated by Django 2.1.1 on 2019-04-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0008_auto_20190405_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='user_address',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='收获地址'),
        ),
    ]
