# Generated by Django 2.1.1 on 2019-04-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0009_traderecord_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='valid_period_display',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='有效期在订单页显示'),
        ),
    ]
