# Generated by Django 2.1.1 on 2019-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0010_auto_20190405_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderecord',
            name='amount',
            field=models.FloatField(verbose_name='交易金额'),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='balance',
            field=models.FloatField(verbose_name='账户余额'),
        ),
    ]
