# Generated by Django 2.1.1 on 2019-04-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0011_auto_20190405_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetail',
            name='course_review',
            field=models.IntegerField(blank=True, null=True, verbose_name='课程评分'),
        ),
    ]
