# Generated by Django 2.1.1 on 2019-04-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0012_coursedetail_course_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetail',
            name='course_review',
            field=models.FloatField(blank=True, null=True, verbose_name='课程评分'),
        ),
    ]
