# Generated by Django 2.1.1 on 2019-04-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0013_auto_20190410_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=32, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='valid_period',
            field=models.SmallIntegerField(choices=[(1, '1天'), (3, '3天'), (7, '1周'), (14, '2周'), (30, '1个月'), (60, '2个月'), (90, '3个月'), (120, '4个月'), (150, '五个月'), (180, '6个月'), (210, '12个月'), (540, '18个月'), (720, '24个月'), (722, '24个月'), (723, '24个月')], verbose_name='课程有效期'),
        ),
    ]
