# Generated by Django 2.1.1 on 2019-04-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0014_auto_20190414_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='brief',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='学员简介'),
        ),
        migrations.AlterField(
            model_name='account',
            name='career',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='目前职业/最近一次从事职业'),
        ),
        migrations.AlterField(
            model_name='account',
            name='education',
            field=models.IntegerField(blank=True, choices=[(0, '大专'), (1, '本科'), (2, '研究生'), (3, '博士'), (4, '硕士'), (5, '其他')], default=5, null=True, verbose_name='学历'),
        ),
    ]
