# Generated by Django 2.1.1 on 2019-04-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0016_auto_20190414_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderecord',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.CharField(blank=True, help_text='如果是支出和退款一定写入购买的商品', max_length=2048, null=True, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='valid_period',
            field=models.SmallIntegerField(choices=[(1, '1天'), (3, '3天'), (7, '1周'), (14, '2周'), (30, '1个月'), (60, '2个月'), (90, '3个月'), (120, '4个月'), (150, '5个月'), (180, '6个月'), (210, '12个月'), (540, '18个月'), (720, '24个月'), (722, '24个月'), (723, '24个月')], verbose_name='课程有效期'),
        ),
    ]
