# Generated by Django 2.1.1 on 2019-04-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0017_auto_20190418_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traderecord',
            name='transaction_number',
        ),
        migrations.RemoveField(
            model_name='traderecord',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='transaction_number',
            field=models.CharField(max_length=128, null=True, verbose_name='流水号'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(0, '收入'), (1, '支出'), (2, '退款'), (3, '提现')], default=1, verbose_name='交易类型'),
        ),
    ]
