# Generated by Django 2.1.1 on 2019-04-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0018_auto_20190418_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='transaction_number',
            field=models.CharField(max_length=128, unique=True, verbose_name='流水号'),
        ),
    ]
