# Generated by Django 2.1.1 on 2019-04-18 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0019_auto_20190418_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderecord',
            name='amount',
            field=models.FloatField(verbose_name='使用账户余额'),
        ),
    ]
