# Generated by Django 2.1.1 on 2019-04-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0020_auto_20190418_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetail',
            options={'verbose_name': '账单详细', 'verbose_name_plural': 'DB_OrderDetail'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.IntegerField(choices=[(0, '通用券'), (1, '抵扣券'), (2, '满减券')], default=0, help_text='通用券为全局优惠券，其他则为专项券'),
        ),
    ]
