# Generated by Django 2.1.1 on 2019-04-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0021_auto_20190420_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_type',
            field=models.SmallIntegerField(choices=[(0, '通用券'), (1, '抵扣券'), (2, '满减券')], default=0, help_text='通用券为全局优惠券，其他则为专项券'),
        ),
        migrations.AlterField(
            model_name='coupondetail',
            name='status',
            field=models.IntegerField(choices=[(0, '未使用'), (1, '已使用'), (2, '已过期')], default=0),
        ),
    ]
