# Generated by Django 2.1.1 on 2019-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0022_auto_20190420_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='contenttypes.ContentType', verbose_name='关联普通课程或学位'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='generic.Order'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='original_price',
            field=models.FloatField(blank=True, null=True, verbose_name='课程原价'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='折后价格'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='流水号'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='valid_period',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='课程有效期(days)'),
        ),
    ]
