# Generated by Django 2.1.1 on 2019-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0023_auto_20190422_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='generic.Order', verbose_name='账单'),
        ),
    ]
