# Generated by Django 2.1.1 on 2019-05-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0025_auto_20190503_1103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生表', 'verbose_name_plural': 'DB_Student'},
        ),
        migrations.AlterModelTable(
            name='student',
            table='DB_Student',
        ),
    ]
