# Generated by Django 2.1.1 on 2019-05-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0026_auto_20190503_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_img',
            field=models.ImageField(blank=True, help_text='填写一个cdn外链地址即可', null=True, upload_to='course/%Y-%m', verbose_name='课程图片'),
        ),
    ]
