# Generated by Django 2.1.1 on 2019-05-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0027_auto_20190503_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete='cascade', to='generic.Category', verbose_name='课程分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_course',
            field=models.ForeignKey(blank=True, help_text='如果是学位课程，必须关联学位表', null=True, on_delete='cascade', to='generic.Degree', verbose_name='学位课程'),
        ),
    ]
