# Generated by Django 2.1.1 on 2019-05-03 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0028_auto_20190503_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete='cascade', related_name='course_chapters', to='generic.Course', verbose_name='课程'),
        ),
    ]
