# Generated by Django 2.1.1 on 2019-05-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0029_auto_20190503_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='level',
            field=models.IntegerField(choices=[(0, '管理员'), (1, '导师'), (2, '学员'), (3, '非学员')], default=3, verbose_name='用户等级'),
        ),
    ]
