# Generated by Django 2.1.1 on 2019-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0030_auto_20190503_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='paid_fee',
            field=models.FloatField(default=0, verbose_name='金额'),
        ),
    ]
