# Generated by Django 2.1.1 on 2019-05-03 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0031_auto_20190503_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentrecord',
            old_name='coures',
            new_name='course',
        ),
    ]
