# Generated by Django 2.1.1 on 2019-05-03 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0032_auto_20190503_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='管理组'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='commonquestion',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='consultant',
            field=models.ForeignKey(limit_choices_to={'account__level': 1}, on_delete=django.db.models.deletion.CASCADE, to='generic.Tutor', verbose_name='跟进人'),
        ),
        migrations.AlterField(
            model_name='consultrecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='所跟进学生'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='coupondetail',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='优惠券拥有者'),
        ),
        migrations.AlterField(
            model_name='coupondetail',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Coupon'),
        ),
        migrations.AlterField(
            model_name='coupondetail',
            name='order',
            field=models.ForeignKey(blank=True, help_text='一个订单可以有多个优惠券使用记录', null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Order', verbose_name='关联订单'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Category', verbose_name='课程分类'),
        ),
        migrations.AlterField(
            model_name='course',
            name='degree_course',
            field=models.ForeignKey(blank=True, help_text='如果是学位课程，必须关联学位表', null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Degree', verbose_name='学位课程'),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_chapters', to='generic.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='coursedetail',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.Course'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_lesson', to='generic.CourseChapter', verbose_name='课程章节'),
        ),
        migrations.AlterField(
            model_name='courseoutline',
            name='course_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_outline', to='generic.CourseDetail'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.PricePolicy', verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'account__level': 1}, on_delete=django.db.models.deletion.CASCADE, to='generic.Tutor', verbose_name='导师'),
        ),
        migrations.AlterField(
            model_name='homeworkdetail',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Homework', verbose_name='作业'),
        ),
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='下单用户'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='关联普通课程或学位'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Order'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='confirm_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='confirms', to='generic.Admins', verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Course', verbose_name='申请课程'),
        ),
        migrations.AlterField(
            model_name='pricepolicy',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='scorerecord',
            name='user',
            field=models.ForeignKey(limit_choices_to={'account__level': 1}, on_delete=django.db.models.deletion.CASCADE, to='generic.Tutor', verbose_name='执行人'),
        ),
        migrations.AlterField(
            model_name='student',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='学员信息'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tutor',
            field=models.ForeignKey(blank=True, help_text='这个字段由管理员填写分配', null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Tutor', verbose_name='导师'),
        ),
        migrations.AlterField(
            model_name='studyquestion',
            name='student',
            field=models.ForeignKey(limit_choices_to={'level': 2}, on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='提问学生'),
        ),
        migrations.AlterField(
            model_name='studyquestion',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'account__level': 1}, on_delete=django.db.models.deletion.CASCADE, to='generic.Tutor', verbose_name='导师'),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='traderecord',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generic.Order', verbose_name='账单'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.Account', verbose_name='导师信息'),
        ),
    ]
