# Generated by Django 2.1.1 on 2019-05-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0033_auto_20190503_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章正文')),
                ('date', models.DateTimeField(verbose_name='发布日期')),
            ],
            options={
                'verbose_name': '资讯文章',
                'verbose_name_plural': 'DB_Article',
                'db_table': 'DB_Article',
            },
        ),
    ]
