# Generated by Django 2.1.1 on 2019-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0035_auto_20190504_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assess_status',
            field=models.IntegerField(choices=[(0, '未评价'), (1, '已评价'), (2, '已追评')], default=0),
        ),
    ]
