# Generated by Django 2.1.1 on 2019-05-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0036_order_assess_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='teacher',
        ),
        migrations.AddField(
            model_name='homeworkdetail',
            name='teacher',
            field=models.ManyToManyField(limit_choices_to={'account__level': 1}, to='generic.Tutor', verbose_name='导师'),
        ),
        migrations.RemoveField(
            model_name='homework',
            name='courses',
        ),
        migrations.AddField(
            model_name='homework',
            name='courses',
            field=models.ManyToManyField(to='generic.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='homeworkdetail',
            name='student',
            field=models.ManyToManyField(blank=True, limit_choices_to={'account__level': 2}, to='generic.Student', verbose_name='学生'),
        ),
    ]
