# Generated by Django 2.1.1 on 2019-05-05 14:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0037_auto_20190505_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyquestion',
            name='answer_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='回答日期'),
        ),
        migrations.AddField(
            model_name='studyquestion',
            name='question_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='提问日期'),
            preserve_default=False,
        ),
    ]
