# Generated by Django 2.1.1 on 2019-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0038_auto_20190505_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='chapter',
            field=models.ManyToManyField(to='generic.CourseChapter', verbose_name='课程章节'),
        ),
    ]
