# Generated by Django 2.1.1 on 2019-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0039_homework_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='作业标题'),
        ),
    ]
