# Generated by Django 2.1.1 on 2019-05-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generic', '0040_homework_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkdetail',
            name='homework',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='generic.Homework', verbose_name='作业'),
        ),
    ]
